table FatRankAdvogados
	lineageTag: ead2553b-11ff-4c5b-a0df-063fa2d2f30f

	column id_rank
		dataType: int64
		formatString: 0
		lineageTag: 2de7d62e-4b94-450a-a0c9-b1856a74a9d2
		summarizeBy: sum
		sourceColumn: id_rank

		annotation SummarizationSetBy = Automatic

	column id_estado
		dataType: int64
		formatString: 0
		lineageTag: 4252ad6c-40b3-4297-8b33-4228d955493d
		summarizeBy: sum
		sourceColumn: id_estado

		annotation SummarizationSetBy = Automatic

	column data_criacao
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7d19493b-49af-4ce5-9a88-147ef1756464
		summarizeBy: none
		sourceColumn: data_criacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column created_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: a0365592-4bb9-4970-9bad-de51890aa15d
		summarizeBy: none
		sourceColumn: created_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column points
		dataType: double
		lineageTag: f1d3dbbd-1c9c-4ef5-8bef-e602f98688e1
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id_advogado
		dataType: int64
		formatString: 0
		lineageTag: de47b235-037d-4f06-8796-28c229c7cc18
		summarizeBy: sum
		sourceColumn: id_advogado

		annotation SummarizationSetBy = Automatic

	column nome_advogado
		dataType: string
		lineageTag: 6ba6ca64-78a1-4960-bb7d-ceadcd530516
		summarizeBy: none
		sourceColumn: nome_advogado

		annotation SummarizationSetBy = Automatic

	partition FatRankAdvogados = m
		mode: import
		source =
				let
				    Fonte = Json.Document(Web.Contents("https://microservices.setuptecnologia.com.br/ms-pbi/adv-rank_lawyers/")),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"id", "state_id", "created_date", "created_time", "points", "item_id", "name"}, {"id", "state_id", "created_date", "created_time", "points", "item_id", "name"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Column1 Expandido",{{"id", Int64.Type}, {"state_id", Int64.Type}, {"created_date", type date}, {"created_time", type time}, {"item_id", Int64.Type}, {"name", type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado",".",",",Replacer.ReplaceText,{"points"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído",{{"points", type number}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"id", "id_rank"}, {"state_id", "id_estado"}, {"created_date", "data_criacao"}, {"item_id", "id_advogado"}, {"name", "nome_advogado"}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Renomeadas", each ([nome_advogado] <> "Alessandra Vieira" and [nome_advogado] <> "Desenvolvimento Setup" and [nome_advogado] <> "Maria Julia Barbosa Moraes Estrella Rael" and [nome_advogado] <> "Rodrigo Rael"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

